### ISSUE TITLE
README.md を書いてみようー

### ISSUE THREAD

**Issue by tegetege** [fu-zzy/fuzzy_AtCoder#1]
README.md にどういうことをやっているリポジトリなのかを書いてみてー

.md は　マークダウン記法で書かれたファイルの拡張子ですー。
README.mdを/fuzzy_AtCoder のディレクトリ以下においてpushすると、Github上でリポジトリにアクセスした時に見れるようになります！！
↓ 僕のtegetege_AtCoderリポジトリのREADME.md
https://github.com/tegetege/tegetege_AtCoder/blob/master/README.md

README.mdをpushして見れるようになったらこのissueをクローズして見てくださいー

**Comment by tegetege** [comment]
参考になりそうなリンク貼っておきまーす

https://qiita.com/tbpgr/items/989c6badefff69377da7

**Comment by fu-zzy** [comment]
# あ
